/**
 * Data constants for profile editing - suggestions, currencies, timezones.
 * Used by CreatablePillInput, CurrencyStringInput, and EditProfileModal.
 */

export const SUGGESTED_SKILLS = [
  "React",
  "TypeScript",
  "JavaScript",
  "Python",
  "Java",
  "Node.js",
  "AWS",
  "Docker",
  "Kubernetes",
  "SQL",
  "PostgreSQL",
  "MongoDB",
  "GraphQL",
  "REST APIs",
  "Git",
  "CI/CD",
  "Terraform",
  "Linux",
  "Agile",
  "Scrum",
  "Redux",
  "Next.js",
  "Vue.js",
  "Angular",
  "FastAPI",
  "Django",
  "Flask",
  "Spring Boot",
  "Go",
  "Rust",
  "C++",
  "C#",
  ".NET",
  "Redis",
  "Elasticsearch",
  "Machine Learning",
  "TensorFlow",
  "PyTorch",
  "Data Structures",
  "Algorithms",
  "System Design",
  "Microservices",
  "Tailwind CSS",
  "HTML",
  "CSS",
  "Sass",
  "Webpack",
  "Jest",
  "Cypress",
  "Figma",
  "Product Management",
  "UX Research",
] as const;

export const SUGGESTED_LANGUAGES = [
  "English",
  "Hindi",
  "Spanish",
  "French",
  "German",
  "Mandarin",
  "Japanese",
  "Korean",
  "Portuguese",
  "Russian",
  "Arabic",
  "Italian",
  "Dutch",
  "Bengali",
  "Tamil",
  "Telugu",
  "Marathi",
  "Gujarati",
  "Punjabi",
  "Vietnamese",
  "Thai",
  "Indonesian",
  "Turkish",
] as const;

export const CURRENCIES = ["USD", "INR", "EUR", "GBP", "CAD", "SGD", "AUD"] as const;

export const TIMEZONES = [
  "Africa/Cairo",
  "Africa/Johannesburg",
  "Africa/Lagos",
  "America/Chicago",
  "America/Denver",
  "America/Los_Angeles",
  "America/New_York",
  "America/Sao_Paulo",
  "America/Toronto",
  "Asia/Bangkok",
  "Asia/Dubai",
  "Asia/Hong_Kong",
  "Asia/Jakarta",
  "Asia/Kolkata",
  "Asia/Seoul",
  "Asia/Singapore",
  "Asia/Shanghai",
  "Asia/Tokyo",
  "Australia/Melbourne",
  "Australia/Sydney",
  "Europe/Amsterdam",
  "Europe/Berlin",
  "Europe/London",
  "Europe/Paris",
  "Europe/Zurich",
  "Pacific/Auckland",
  "UTC",
] as const;
