import type { Metadata } from "next";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { AuthGuardProvider } from "@/components/guards/AuthGuardProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Adzzat Jobs",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/icon.png", sizes: "32x32", type: "image/png" },
      { url: "/icon.png", sizes: "16x16", type: "image/png" },
      { url: "/icon.png", sizes: "48x48", type: "image/png" },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased" suppressHydrationWarning>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <AuthGuardProvider>{children}</AuthGuardProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
